# Generated by Django 5.2.1 on 2025-10-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=80, max_length=70),
            preserve_default=False,
        ),
    ]
