# Generated by Django 5.2.1 on 2025-10-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0002_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
