FROM python:3.13.5

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    DEBIAN_FRONTEND=noninteractive

WORKDIR /productService

# OS deps for mysqlclient
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    pkg-config \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt

# install Python deps
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# copy the rest of your app (do this after deps for better layer caching)
COPY . .
