# Generated by Django 5.2.1 on 2025-10-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
