# Generated by Django 5.2.1 on 2025-10-29 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('pages', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_info', to='products.product')),
            ],
        ),
    ]
